sudo: required
language: cpp

notifications:
      email: false
      
before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt58
  - sudo apt-get update -q
  - sudo apt-get install -qq qt58-meta-full

script:
  - mkdir build
  - cd build
  - cmake ..
