sudo: required
language: cpp
dist: trusty

notifications:
      email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - g++-6
      - lcov

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt58-trusty
  - sudo apt-get update -q
  - travis_wait 30 sudo apt-get install -qq qt58-meta-full

script:
  - source /opt/qt58/bin/qt58-env.sh
  - mkdir build-g64 build-c64
# GCC x64
  - cd build-g64
  - export CC=gcc-6
  - export CXX=g++-6
  - cmake .. -DWITH_COVERAGE=ON
  - make -j4
  - ctest -V
  #- lcov --directory . --capture --output-file coverage.info # capture coverage info
  #- lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  #- lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
# Clang x64
  #- cd ../build-c64
  #- export CC=clang
  #- export CXX=clang++
  #- cmake ..
  #- make -j4
  
